switch01:
  data:
    interfaces:
      - name: Vlan10
        description: Management
        ip: 10.0.10.1
        mask: 255.255.255.0
switch02:
  data:
    interfaces:
      - name: Vlan10
        description: Management
        ip: 10.0.10.2
        mask: 255.255.255.0
switch03:
  data:
    interfaces:
      - name: Vlan10
        description: Management
        ip: 10.0.10.3
        mask: 255.255.255.0